# Generated by Django 5.2.4 on 2025-07-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentorshipmatch_is_active_module_notes_module_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age_group', models.CharField(choices=[('7-12', '7–12'), ('13-15', '13–15'), ('16-18', '16–18')], max_length=20)),
                ('content_type', models.CharField(choices=[('game', 'Game'), ('cartoon', 'Cartoon'), ('lesson', 'Lesson'), ('health_tip', 'Health Tip'), ('quiz', 'Quiz')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='confidencelog',
            name='suggestion_given',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('marketing', 'Digital Marketing'), ('entrepreneurship', 'Entrepreneurship'), ('soft_skills', 'Soft Skills'), ('finance', 'Financial Literacy')], max_length=50),
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='materials/videos/')),
                ('notes', models.FileField(blank=True, null=True, upload_to='materials/notes/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='materials/pdfs/')),
                ('article', models.TextField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.educationalcontent')),
            ],
        ),
    ]
