# Generated by Django 5.2.4 on 2025-07-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_educationalcontent_confidencelog_suggestion_given_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBasedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AgeBasedTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('tip', models.TextField()),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StructuredContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.AddField(
            model_name='progress',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
