# Generated by Django 5.2.4 on 2025-07-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agebasedcontent_agebasedtip_structuredcontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=50)),
                ('tip', models.TextField()),
            ],
        ),
    ]
